import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Mynavbar from "@/component/Mynavbar";
import Footer from "@/component/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Mynavbar />
        </header>
        <section>
          {children}
        </section>
        <footer className="bg-[#151e28]">
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
